#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("test.Resource", IsApplication=true)]

namespace test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int black = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int groupHeaderTextColor = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int listAccentColor = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int listItemTextColor = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int pressedColor = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int selectionColor = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int shadeColor = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int shadeColorCenter = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int transparent = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int white = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040001
			public const int card_deck_translation = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gingerbread_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_collapse = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_expand = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pressable_item_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int selectable_item_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int shade_bottom = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int shade_corner = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int shade_right = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int test_img = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int countryView = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int groupHeaderCollapseImage = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int groupHeaderText = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int imgPoster = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int listView = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int nameView = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int scrollingLayout = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int separator = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int text1 = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int city_list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_list_view_slide = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int on_demand_automatic = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int on_demand_manual = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int simple_empty_content = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int simple_group_header_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int simple_list_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int trial_message = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070006
			public const int app_name = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int hello = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int list_view_default_empty_content = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int on_demand_manual_button_busy = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int on_demand_manual_button_idle = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int trial_message = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int trial_message_caption = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
